# Generated by Django 3.0.5 on 2020-11-15 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegramaccount',
            options={'verbose_name': 'Телеграм пользователь', 'verbose_name_plural': 'Телеграм пользователи'},
        ),
        migrations.AlterField(
            model_name='telegramaccount',
            name='real_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Баланс (рубли)'),
        ),
        migrations.AlterField(
            model_name='telegramaccount',
            name='source',
            field=models.CharField(default='default', max_length=50, verbose_name='Кто привел пользователя'),
        ),
        migrations.AlterField(
            model_name='telegramaccount',
            name='tg_id',
            field=models.PositiveIntegerField(unique=True, verbose_name='Телеграм юзер ID'),
        ),
        migrations.AlterField(
            model_name='telegramaccount',
            name='virtual_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Баланс (Бонусные жетоны)'),
        ),
    ]
