# Generated by Django 3.0.5 on 2020-09-07 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramaccount',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='telegramaccount',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='telegramaccount',
            name='username',
        ),
        migrations.AddField(
            model_name='telegramaccount',
            name='real_balance',
            field=models.PositiveIntegerField(default=0, verbose_name='Real balance amount'),
        ),
        migrations.AddField(
            model_name='telegramaccount',
            name='source',
            field=models.CharField(default='default', max_length=50, verbose_name='Source of user'),
        ),
        migrations.AddField(
            model_name='telegramaccount',
            name='virtual_balance',
            field=models.PositiveIntegerField(default=0, verbose_name='Virtual balance amount'),
        ),
    ]
