# Generated by Django 3.0.5 on 2020-11-17 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20201115_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramaccount',
            name='first_name',
            field=models.CharField(default=' ', max_length=255, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='telegramaccount',
            name='last_name',
            field=models.CharField(default=' ', max_length=255, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='telegramaccount',
            name='username',
            field=models.CharField(default=' ', max_length=255, verbose_name='Юзернейм'),
        ),
    ]
