# Generated by Django 3.0.5 on 2020-11-22 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20201117_1219'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegramaccount',
            options={'verbose_name': 'Телеграм пользователя', 'verbose_name_plural': 'Телеграм пользователи'},
        ),
    ]
