# Generated by Django 3.0.5 on 2020-12-29 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20201122_0205'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramaccount',
            name='max_withdrawal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Доступная сумма к выводу'),
        ),
    ]
