# Generated by Django 3.0.5 on 2020-11-20 00:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('abtest', '0004_botprofile_onboarding'),
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('text', models.TextField(verbose_name='Текст рассылки')),
                ('broadcast_to_all', models.BooleanField(default=False, verbose_name='Отправить всем')),
                ('action', models.CharField(choices=[('queue_for_sending', 'Поставить в очередь на рассылку'), ('await', 'Перевести в ожидание')], max_length=55, verbose_name='Применить действие')),
                ('timedelta_inactive', models.DurationField(choices=[(datetime.timedelta(0), 'Не использовать параметр'), (datetime.timedelta(days=1), 'Один день'), (datetime.timedelta(days=3), 'Три дня'), (datetime.timedelta(days=7), '7 дней'), (datetime.timedelta(days=30), 'Тридцать дней')], default=0, verbose_name='Неактивность больше чем')),
                ('status', models.BooleanField(default=False, verbose_name='Выполно/Не выполнено')),
                ('bot_profile', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='abtest.BotProfile', verbose_name='Выбрать A\\B профиль кому рассылать')),
            ],
            options={
                'verbose_name': 'Сообщение на рассылку',
                'verbose_name_plural': 'Рассылка сообщений',
            },
        ),
    ]
