# Generated by Django 3.0.5 on 2021-01-11 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcast', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcastquery',
            name='update_keyboard',
            field=models.BooleanField(default=False, verbose_name='Обновить клавиатуру'),
        ),
    ]
