# Generated by Django 3.0.5 on 2021-01-14 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcast', '0002_broadcastquery_update_keyboard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='broadcastquery',
            name='update_keyboard',
        ),
        migrations.AddField(
            model_name='broadcastquery',
            name='keyboard',
            field=models.CharField(choices=[('none', 'Не обновлять клавиатуру'), ('start', 'Основная клавиатура'), ('invite', 'Пригласить друга'), ('games', 'Игры')], default='none', max_length=50, verbose_name='Обновить клавиатуру'),
        ),
    ]
