# Generated by Django 3.0.5 on 2021-01-04 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0002_auto_20210104_0538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affiliatesetup',
            name='type_referral_deposit_bonus',
        ),
        migrations.AlterField(
            model_name='affiliatesetup',
            name='referral_deposit_bonus',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Коэффициент рефералу на первое пополнение депозита'),
        ),
    ]
