version: "3.5"

services:
  postgres:
    image: postgres:11
    volumes:
      - pg_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=core_db
    ports:
      - "5432:5432"
  redis:
    restart: always
    image: redis:alpine
    depends_on:
      - postgres
    expose:
      - "6379"
    volumes:
    - cache:/src/redis/cache
  api:
    build:
      context: ./../  # games-bot
      dockerfile: docker/images/api/Dockerfile
    ports:
      - 8000:8080
    depends_on:
      - postgres
      - redis
    volumes:
      - static_volume:/src/public/static
      - cache:/src/redis/cache
      - gsheets:/src/gsheets
    environment:
      - CORE_DATABASE_WAIT=1
      - CORE_DATABASE_URL=psql://postgres:postgres@postgres:5432/core_db
    image: docker_api
  bot:
    build:
      context: ./../  # games-bot
      dockerfile: docker/images/bot/Dockerfile
    environment:
      - BOT_TOKEN
    depends_on:
      - api
    volumes:
    - cache:/src/redis/cache
  celery_worker:
    restart: on-failure
    build:
      context: ./../
      dockerfile: docker/images/celery/Dockerfile
    command: ["python", '-m', "celery", "-A", "core.config", "worker", "-l", "info"]
    depends_on:
      - api
    environment:
      - CORE_DATABASE_WAIT=1
      - CORE_DATABASE_URL=psql://postgres:postgres@postgres:5432/core_db
    image: docker_celery
  celery_beat:
    restart: on-failure
    command: [ "python", '-m', "celery", "--pidfile=", "-A", "core.config", "beat", "-l", "info", "--scheduler", "django_celery_beat.schedulers:DatabaseScheduler" ]
    depends_on:
      - api
    environment:
      - CORE_DATABASE_WAIT=1
      - CORE_DATABASE_URL=psql://postgres:postgres@postgres:5432/core_db
    image: docker_celery

volumes:
  pg_data:
  static_volume:
  cache:
  gsheets:
