# Generated by Django 3.0.5 on 2020-11-15 18:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='withdrawrequest',
            options={'verbose_name': 'Запрос на вывод', 'verbose_name_plural': 'Запросы на вывод'},
        ),
        migrations.AlterField(
            model_name='withdrawrequest',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=9, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000)], verbose_name='Сумма вывода'),
        ),
        migrations.AlterField(
            model_name='withdrawrequest',
            name='card_number',
            field=models.CharField(max_length=20, verbose_name='Номер карты'),
        ),
        migrations.AlterField(
            model_name='withdrawrequest',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен/Неактивен'),
        ),
        migrations.AlterField(
            model_name='withdrawrequest',
            name='status',
            field=models.CharField(choices=[('accepted', 'Withdraw request accepted'), ('rejected', 'Withdraw request rejected'), ('in_progress', 'Withdraw request in progress')], default='in_progress', max_length=50, verbose_name='Статус запроса'),
        ),
    ]
