# Generated by Django 3.0.5 on 2020-11-26 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_auto_20201115_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawrequest',
            name='status',
            field=models.CharField(choices=[('accepted', 'Запрос на снятие средств выполнен'), ('rejected', 'Запрос на снятие средств отклонен'), ('in_progress', 'Запрос на снятие средств выполняется')], default='in_progress', max_length=50, verbose_name='Статус запроса'),
        ),
    ]
