# Generated by Django 3.0.5 on 2020-09-19 12:48

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceMultiplierConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('amount_from', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=9, verbose_name='Amount from')),
                ('amount_to', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=9, verbose_name='Amount to')),
                ('multiplier', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=5, verbose_name='Multiplier')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'unique_together': {('amount_from', 'amount_to', 'is_active')},
            },
        ),
    ]
