# Generated by Django 3.0.5 on 2020-09-19 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancemultiplierconfig',
            name='amount_from',
            field=models.PositiveIntegerField(default=0, verbose_name='Amount from'),
        ),
        migrations.AlterField(
            model_name='balancemultiplierconfig',
            name='amount_to',
            field=models.PositiveIntegerField(default=0, verbose_name='Amount to'),
        ),
    ]
