# Generated by Django 3.0.5 on 2021-01-04 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_settings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name': 'Настройки', 'verbose_name_plural': 'Настройки'},
        ),
        migrations.AlterField(
            model_name='settings',
            name='min_deposit',
            field=models.PositiveIntegerField(verbose_name='Минимальная сумма депозита'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='min_withdrawal',
            field=models.PositiveIntegerField(verbose_name='Минимальная сумма вывода'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='wager',
            field=models.PositiveIntegerField(verbose_name='Вагер'),
        ),
    ]
