# Generated by Django 3.0.5 on 2020-11-15 17:25

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramAccountStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('tg_id', models.PositiveIntegerField(verbose_name='Telegram user ID')),
                ('source', models.CharField(default='none', max_length=255, verbose_name='Source user')),
                ('type_action', models.CharField(max_length=255, verbose_name='Type action')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='Data action')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
