# Generated by Django 3.0.5 on 2020-11-22 02:05

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegramaccountstatistic',
            options={'verbose_name': 'запись в статистике телеграм аккаунтов', 'verbose_name_plural': 'Статистика Телеграм Аккаунтов'},
        ),
        migrations.AddField(
            model_name='telegramaccountstatistic',
            name='first_name',
            field=models.CharField(default='[отсутствует]', max_length=255, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='telegramaccountstatistic',
            name='last_name',
            field=models.CharField(default='[отсутствует]', max_length=255, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='telegramaccountstatistic',
            name='username',
            field=models.CharField(default='[отсутствует]', max_length=255, verbose_name='Юзернейм'),
        ),
        migrations.AlterField(
            model_name='telegramaccountstatistic',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(verbose_name='Информация о событии'),
        ),
        migrations.AlterField(
            model_name='telegramaccountstatistic',
            name='source',
            field=models.CharField(default='none', max_length=255, verbose_name='Кто привел пользователя'),
        ),
        migrations.AlterField(
            model_name='telegramaccountstatistic',
            name='tg_id',
            field=models.PositiveIntegerField(verbose_name='Телеграм Юзер ID'),
        ),
        migrations.AlterField(
            model_name='telegramaccountstatistic',
            name='type_action',
            field=models.CharField(max_length=255, verbose_name='Тип события'),
        ),
    ]
