# Generated by Django 3.0.5 on 2021-01-10 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abtest', '0009_botprofile_type_deposit_bonus'),
        ('statistic', '0002_auto_20201122_0205'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatisticRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('source_list', models.CharField(blank=True, max_length=250, null=True, verbose_name='Указать название каналов через запятую')),
                ('all_user', models.BooleanField(default=False, verbose_name='Статистика по всем пользователям')),
                ('type_setup', models.CharField(choices=[('default', 'Общая статистика')], default='default', max_length=50, verbose_name='Тип выгружаемой статистики')),
                ('date_1', models.DateTimeField(blank=True, null=True, verbose_name='Дата 1')),
                ('date_2', models.DateTimeField(blank=True, null=True, verbose_name='Дата 2')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='abtest.SourceSetup', verbose_name='Выбрать канал')),
            ],
            options={
                'verbose_name': 'Выгрузка статистики',
                'verbose_name_plural': 'Выгрузка статистики',
            },
        ),
    ]
