# Generated by Django 3.0.5 on 2021-01-17 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0003_statisticrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statisticrequest',
            name='type_setup',
            field=models.CharField(choices=[('default', 'Общая статистика пользователей'), ('common', 'Общая статистика бота'), ('top_games', 'Топ игр')], default='default', max_length=50, verbose_name='Тип выгружаемой статистики'),
        ),
    ]
