# Generated by Django 3.0.5 on 2020-11-15 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('order_id', models.PositiveIntegerField(unique=True)),
                ('tg_id', models.PositiveIntegerField()),
                ('amount', models.PositiveIntegerField()),
                ('payment_api', models.CharField(default='FreeKassa', max_length=255)),
                ('status', models.CharField(default='new', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
