# Generated by Django 3.0.5 on 2020-11-15 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotProfile',
            fields=[
                ('name', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('version_text', models.CharField(max_length=25)),
                ('welcome_bonus', models.FloatField()),
                ('deposit_bonus', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='BotText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('text', models.TextField()),
                ('text_ru', models.TextField(null=True)),
                ('text_en', models.TextField(null=True)),
                ('version', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='SourceSetup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abtest.BotProfile')),
            ],
        ),
    ]
