# Generated by Django 3.0.5 on 2020-11-15 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abtest', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='botprofile',
            options={'verbose_name': 'A/B профиль', 'verbose_name_plural': 'A/B профили'},
        ),
        migrations.AlterModelOptions(
            name='bottext',
            options={'verbose_name': 'Текст', 'verbose_name_plural': 'Текста бота'},
        ),
        migrations.AlterModelOptions(
            name='sourcesetup',
            options={'verbose_name': 'Конфигурация источника трафика', 'verbose_name_plural': 'Конфигурации'},
        ),
        migrations.AlterField(
            model_name='botprofile',
            name='deposit_bonus',
            field=models.FloatField(verbose_name='Бонус на депозит'),
        ),
        migrations.AlterField(
            model_name='botprofile',
            name='name',
            field=models.CharField(max_length=25, primary_key=True, serialize=False, verbose_name='Имя профиля'),
        ),
        migrations.AlterField(
            model_name='botprofile',
            name='version_text',
            field=models.CharField(max_length=25, verbose_name='Версия текста'),
        ),
        migrations.AlterField(
            model_name='botprofile',
            name='welcome_bonus',
            field=models.FloatField(verbose_name='Вступительный бонус'),
        ),
        migrations.AlterField(
            model_name='bottext',
            name='name',
            field=models.CharField(max_length=55, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='bottext',
            name='text',
            field=models.TextField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='bottext',
            name='text_en',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='bottext',
            name='text_ru',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='sourcesetup',
            name='name',
            field=models.CharField(max_length=55, verbose_name='Название источника трафика'),
        ),
        migrations.AlterField(
            model_name='sourcesetup',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abtest.BotProfile', verbose_name='A/B тест профиль'),
        ),
    ]
