# Generated by Django 3.0.5 on 2020-11-16 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abtest', '0002_auto_20201115_1843'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bottext',
            options={'verbose_name': 'Текст', 'verbose_name_plural': 'Тексты бота'},
        ),
    ]
