# Generated by Django 3.0.5 on 2020-11-17 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abtest', '0003_auto_20201116_0416'),
    ]

    operations = [
        migrations.AddField(
            model_name='botprofile',
            name='onboarding',
            field=models.BooleanField(default=True, verbose_name='Вступительное обучение'),
        ),
    ]
