# Generated by Django 3.0.5 on 2020-11-28 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abtest', '0004_botprofile_onboarding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcesetup',
            name='name',
            field=models.CharField(max_length=55, unique=True, verbose_name='Название источника трафика'),
        ),
    ]
