# Generated by Django 3.0.5 on 2020-12-29 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abtest', '0008_auto_20201208_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='botprofile',
            name='type_deposit_bonus',
            field=models.CharField(choices=[('factor', 'Множитель'), ('fixed', 'Фиксированный')], default='factor', max_length=255, verbose_name='Тип бонуса на депозит'),
        ),
    ]
