# Generated by Django 3.0.5 on 2020-11-15 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('game_id', models.PositiveIntegerField(verbose_name='Game ID')),
                ('invoice_id', models.CharField(max_length=250, verbose_name='Invoice ID')),
                ('tr_id', models.CharField(max_length=250, verbose_name='Transaction ID')),
                ('type_invoice', models.CharField(max_length=250, verbose_name='Type invoice')),
                ('start_real_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('start_virtual_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('end_real_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('end_virtual_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('last_check_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(default='open', max_length=250, verbose_name='Status')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='account.TelegramAccount')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
