# Generated by Django 3.0.5 on 2020-12-29 16:36

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicedata',
            name='game_history',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
    ]
