---

- name: Setup git repo
  become: yes
  become_user: "{{ user }}"
  git: repo={{ git_repo }}
       version={{ git_branch }}
       dest={{ project_src }}
       accept_hostkey=yes
       force=yes
       recursive=no
  tags: git
  register: git_repo

- name: Start app
  docker_compose:
    files:
      - live.yml
    project_src: "{{ docker_path }}"
    build: yes
    remove_orphans: yes
